#!/bin/env bash

set -euo pipefail

# Ensure brightnessctl is installed
if ! command -v brightnessctl &>/dev/null; then
    echo "Error: brightnessctl not found. Please install it first."
    exit 1
fi

opt="${1:-}"
num="${2:-5}"
status="restatus rt 2"

function brightness_inc() {
    if [[ "${num}" =~ ^[0-9]+$ ]]; then
        brightnessctl set "${num}%+"
    else
        exit 1
    fi
    $status
}

function brightness_dec() {
    if [[ "${num}" =~ ^[0-9]+$ ]]; then
        brightnessctl set "${num}%-"
    else
        exit 1
    fi
    $status
}

function help_menu() {
    cat << EOF
    Usage: $(basename "$0") [Options]

Options:
  --help, -h             Show this help message
  --inc, -i \${num}      increase brightness by [Amount] or 5 if not specified
  --dec, -d \${num}      decrease brightness by [Amount] or 5 if not specified
EOF
}

case "$opt" in
    --inc|-i)
        brightness_inc "${num}"
        ;;
    --dec|-d)
        brightness_dec "${num}"
        ;;
    --help|-h)
        help_menu
        ;;
    *)
        echo "Error: '${opt:- }' Invalid option."
        help_menu
        exit 1
        ;;
esac
