#!/bin/env bash

set -euo pipefail

# Ensure brightnessctl is installed
if ! command -v brightnessctl &>/dev/null; then
    echo "Error: brightnessctl not found. Please install it first."
    exit 1
fi

opt="${1:-}"
num="${2:-5}"
cmd="restatus 15 dwmblocks"

function brightness_inc() {
    if [[ "${num}" =~ ^[0-9]+$ ]]; then
        brightnessctl set "${num}%+"
        $cmd
    else
        exit 1
    fi
}

function brightness_dec() {
    if [[ "${num}" =~ ^[0-9]+$ ]]; then
        brightnessctl set "${num}%-"
        $cmd
    else
        exit 1
    fi

}

function brightness_get() {
    line="$(brightnessctl | grep "%")"
    brightness_raw=$(echo "$line" | grep -oP '\(\K[0-9]+%')
    brightness=${brightness_raw%\%}

    if [[ "$brightness" -eq 100 ]]; then
        echo "󰛨  ${brightness_raw}"
    elif [[ "$brightness" -ge 90 ]]; then
        echo "󱩖 ${brightness_raw}"
    elif [[ "$brightness" -ge 80 ]]; then
        echo "󱩖 ${brightness_raw}"
    elif [[ "$brightness" -ge 70 ]]; then
        echo "󱩕 ${brightness_raw}"
    elif [[ "$brightness" -ge 60 ]]; then
        echo "󱩔 ${brightness_raw}"
    elif [[ "$brightness" -ge 50 ]]; then
        echo "󱩓 ${brightness_raw}"
    elif [[ "$brightness" -ge 40 ]]; then
        echo "󱩒 ${brightness_raw}"
    elif [[ "$brightness" -ge 30 ]]; then
        echo "󱩑 ${brightness_raw}"
    elif [[ "$brightness" -ge 20 ]]; then
        echo "󱩐 ${brightness_raw}"
    elif [[ "$brightness" -ge 10 ]]; then
        echo "󱩏 ${brightness_raw}"
    elif [[ "$brightness" -ge 0 ]]; then
        echo "󱩎 ${brightness_raw}"
    else
        echo "󰹐 "
    fi
}

function help_menu() {
    cat << EOF
    Usage: $(basename "$0") [Options]

Options:
  --help, -h             Show this help message
  --inc, -i \${num}      increase brightness by [Amount] or 5 if not specified
  --dec, -d \${num}      decrease brightness by [Amount] or 5 if not specified
  --get, -g              get current brightness
EOF
}

case "$opt" in
    --inc|-i)
        brightness_inc "${num}"
        ;;
    --dec|-d)
        brightness_dec "${num}"
        ;;
    --get|-g)
        brightness_get
        ;;
    --help|-h)
        help_menu
        ;;
    *)
        echo "Error: '${opt:- }' Invalid option."
        help_menu
        exit 1
        ;;
esac
