#!/bin/env bash

# Ensure brightnessctl is installed
if ! command -v brightnessctl &>/dev/null; then
    echo "Error: brightnessctl not found. Please install it first."
    exit 1
fi

brightness_inc() {
    brightnessctl set "${1}%+"
}

brightness_dec() {
    brightnessctl set "${1}%-"
}

brightness_get() {
    line="$(brightnessctl | grep "%")"
    brightness_raw=$(echo "$line" | grep -oP '\(\K[0-9]+%')
    brightness=${brightness_raw%\%}

    if [[ "$brightness" -eq 100 ]]; then
        echo "󰛨  ${brightness_raw}"
    elif [[ "$brightness" -ge 90 ]]; then
        echo "󱩖 ${brightness_raw}"
    elif [[ "$brightness" -ge 80 ]]; then
        echo "󱩖 ${brightness_raw}"
    elif [[ "$brightness" -ge 70 ]]; then
        echo "󱩕 ${brightness_raw}"
    elif [[ "$brightness" -ge 60 ]]; then
        echo "󱩔 ${brightness_raw}"
    elif [[ "$brightness" -ge 50 ]]; then
        echo "󱩓 ${brightness_raw}"
    elif [[ "$brightness" -ge 40 ]]; then
        echo "󱩒 ${brightness_raw}"
    elif [[ "$brightness" -ge 30 ]]; then
        echo "󱩑 ${brightness_raw}"
    elif [[ "$brightness" -ge 20 ]]; then
        echo "󱩐 ${brightness_raw}"
    elif [[ "$brightness" -ge 10 ]]; then
        echo "󱩏 ${brightness_raw}"
    elif [[ "$brightness" -ge 0 ]]; then
        echo "󱩎 ${brightness_raw}"
    else
        echo "󰹐 "
    fi
}


case "$1" in
    --inc)
        if [[ "$2" =~ ^[0-9]+$ ]]; then
            brightness_inc "$2"
            pkill -RTMIN+15 slstatus
        else
            echo "Usage: $0 --inc <amount>"
            exit 1
        fi
        ;;
    --dec)
        if [[ "$2" =~ ^[0-9]+$ ]]; then
            brightness_dec "$2"
            pkill -RTMIN+15 slstatus
        else
            echo "Usage: $0 --dec <amount>"
            exit 1
        fi
        ;;
    --get)
        brightness_get
        ;;
    *)
        echo "Unknown argument: $1"
        echo "Usage: $0 --inc|--dec <amount> | --get"
        exit 1
        ;;
esac
