#!/bin/env bash

set -euo pipefail

# Source utils
[[ -f "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils" ]] && source "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils"

player="${1:-}"

if [[ -z "$player" ]]; then
    echo "Usage: $(basename "$0") player"
    exit 1
fi

status="${STATUSBAR:-dwmblocks}"
cmd="restatus 13 $status"

playerctl --player="$player" metadata title >/dev/null && $cmd || break
