#!/bin/env bash

# dmenu_themer
# A dmenu wrapper for theming

CHOICE=$(echo -e "nord\ngruvbox" | dmenu -p "Theme:")

case $CHOICE in
    nord) st -e zsh -c "themer.sh nord" ;;
    gruvbox) st -e zsh -c "themer.sh gruvbox" ;;
    *)
        echo "Invalid choice"
        exit 1
        ;;
esac
