#!/bin/env bash

# Get the list of open windows (you can change this to match the format you like)
window_list=$(wmctrl -l | awk '{$1=""; print substr($0,2)}')

# Use dmenu to select the window
selected_window=$(echo "$window_list" | dmenu -i -p "Switch to:")

# Focus the selected window
if [ -n "$selected_window" ]; then
    # Get the window ID by looking it up again with wmctrl
    window_id=$(wmctrl -l | grep "$selected_window" | awk '{print $1}')
    # Focus the selected window using wmctrl
    wmctrl -i -a "$window_id"
fi
