#!/bin/env bash

# dmenu prompt
options="Lock\nLogout\nReboot\nShutdown"
choice=$(echo -e "$options" | dmenu -p "Power Menu")

case "$choice" in
    Lock)
        slock
        ;;
    Logout)
        xkill -9 "$(pidof Xorg)"
        ;;
    Reboot)
        systemctl reboot
        ;;
    Shutdown)
        systemctl poweroff
        ;;
    *)
        ;;
esac
