#!/bin/env bash
emoji=$(dmenu-emoji | dmenu -l 10 -p "What Emoji? "| awk '{print $1}' | tr -d '\n' )
if [[ -n "$emoji" ]]; then
    echo -n "$emoji" | xclip -selection clipboard
    notify-send "Copied to clipboard!" "Emoji: $emoji"
fi
