#!/bin/env bash

# Main Tracks
pactl load-module module-null-sink sink_name="main_track" sink_properties=device.description="Main_Track"
pactl load-module module-loopback latency_msec=1 source=main_track.monitor sink=alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink

# Switch Tracks
pactl load-module module-null-sink sink_name="switch_track" sink_properties=device.description="Switch_Track"
pactl load-module module-loopback latency_msec=1 source=alsa_input.usb-MACROSILICON_USB3.0_Capture_20210623-02.analog-stereo sink=alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink

# Music Tracks
pactl load-module module-null-sink sink_name="music_track" sink_properties=device.description="Music_Track"
pactl load-module module-loopback latency_msec=1 source=music_track.monitor sink=alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink

notify-send "Loopback Devices Loaded"
