#!/bin/env bash

set -euo pipefail

outputloc="$1"
now="$2"

if [[ ! -d "$outputloc" || -z "$now" ]]; then
    echo "Usage: $0 <output_directory> <timestamp>"
    exit 1
fi

ffmpeg \
    -i "${outputloc}/vid/video_${now}.mkv" \
    -i "${outputloc}/aud/mic_${now}.wav" \
    -i "${outputloc}/aud/desktop_${now}.wav" \
    -filter_complex "[1:a][2:a]amix=inputs=2:duration=shortest[aout]" \
    -map 0:v -metadata:s:v:0 title="Screen" \
    -map "[aout]" -metadata:s:a:0 title="Mixed Audio" -disposition:a:0 default \
    -map 1:a -metadata:s:a:1 title="Microphone" -disposition:a:1 0 \
    -map 2:a -metadata:s:a:2 title="System Audio" -disposition:a:2 0 \
    -c:v copy -c:a aac -shortest "${outputloc}/final.mkv"
