#!/bin/env bash

if [[ -z $1 ]]; then
    printf "File Name: "
    read -r ans
else
    ans=$1
fi

file=$HOME/Scripts/$ans
if [ -d "$HOME/Scripts" ]; then
    if [ -e "$HOME/Scripts/$ans" ]; then
        $EDITOR "$file"
    else
        echo "#!/bin/env bash" >> "$file"
        chmod a+x "$file"
        $EDITOR "$file"
    fi
fi
