#!/bin/env bash

set -euo pipefail

if [[ -z "$1" ]]; then
    echo "Usage: pip <file>"
    exit 1
fi

mpv "$1" \
    --geometry=25%x25%-8-8 \
    --volume=45 \
    --ontop \
    --osc=no \
    --no-border \
    --window-dragging=yes \
    --x11-name=PipWin
