#!/bin/env bash

# Source utils
[[ -f "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils" ]] && source "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils"

# Restart
if [[ "$WM" == "dwm" ]]; then
    pkill dwm
    if [[ "$STATUSBAR" == "dwmblocks" ]]; then
        ${STATUSBAR} & disown
    elif [[ "$STATUSBAR" == "slstatus" ]]; then
        pkill "${STATUSBAR}"
        ${STATUSBAR} & disown
    fi
else
    notify-send "This ${WM} is not dwm"
fi
