#!/bin/env bash
wm="$(ps -e -o comm= | grep -E 'dwm|bspwm|xmonad|awesome|kwin' | grep -v dwmblocks | head -n 1 | xargs)"
if [[ $wm = "dwm" ]]; then
    pkill dwm
else
    notify-send "This ${wm} is not dwm"
fi
