#!/bin/env bash

# Ensure ffmpeg is installed
if ! command -v ffmpeg &> /dev/null; then
    echo "Error: ffmpeg not found. Please install it first."
    exit 1
fi

# Source utils
[[ -f "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils" ]] && \
    source "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils"

status="${STATUSBAR:-dwmblocks}"
cmd="restatus 12 $status"

function record() {
    # Create output directory
    now="$(date '+%a__%b%d__%H_%M_%S')"
    outputloc="$HOME/Videos/video_${now}"
    mkdir -p "$outputloc"/{vid,aud}

    # Detect primary monitor
    primary_info=$(xrandr | awk '/ primary / {print $4}')
    res=${primary_info%%+*}
    offset=${primary_info#*+}
    offset=${offset//+/,}

    # Screen capture only the primary monitor
    ffmpeg -video_size "$res" -f x11grab -r 30 -i "$DISPLAY+${offset}" -c:v h264 -qp 0 \
        "${outputloc}/vid/video_${now}.mkv" &
    echo $! > /tmp/recpid

    # Microphone (Default input monitor)
    ffmpeg -f pulse -i default \
        -af "afftdn=nf=-75" \
        "${outputloc}/aud/mic_${now}.wav" &
    echo $! > /tmp/audpid

    # Desktop audio (Default output monitor)
    ffmpeg -f pulse -i default.monitor \
        "${outputloc}/aud/desktop_${now}.wav" &
    echo $! > /tmp/deskaudpid

    # Metadata
    echo "$now" > /tmp/recording_timestamp
    echo "$outputloc" > /tmp/recording_outputdir
    echo "󰑊 Recording" > /tmp/recordingicon && $cmd

    notify-send "Recording started"
}

function end() {
    kill -15 "$(cat /tmp/recpid)" "$(cat /tmp/audpid)" "$(cat /tmp/deskaudpid)"
    wait

    $cmd

    now=$(cat /tmp/recording_timestamp)
    outputloc=$(cat /tmp/recording_outputdir)

    notify-send "Recording ended, now merging"

    # Call merge script to merge recording files
    ffmpeg \
        -i "${outputloc}/vid/video_${now}.mkv" \
        -i "${outputloc}/aud/mic_${now}.wav" \
        -i "${outputloc}/aud/desktop_${now}.wav" \
        -filter_complex "[1:a][2:a]amix=inputs=2:duration=shortest[aout]" \
        -map 0:v -metadata:s:v:0 title="Screen" \
        -map "[aout]" -metadata:s:a:0 title="Mixed Audio" -disposition:a:0 default \
        -map 1:a -metadata:s:a:1 title="Microphone" -disposition:a:1 0 \
        -map 2:a -metadata:s:a:2 title="System Audio" -disposition:a:2 0 \
        -c:v copy -c:a aac -shortest "${outputloc}/final.mkv"


    rm -fv /tmp/recordingicon /tmp/*pid /tmp/recording_timestamp /tmp/recording_outputdir

    notify-send "Recording merged"
}

# If the recording pid exists, end recording. If not, start recording
([[ -f /tmp/recpid ]] && end && exit 0) || record
