#!/bin/env bash

# Source utils
[[ -f "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils" ]] && source "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils"

# Ensure ffmpeg is installed
if ! command -v ffmpeg &> /dev/null; then
    echo "Error: ffmpeg not found. Please install it first."
    exit 1
fi

status="${STATUSBAR:-dwmblocks}"
cmd="restatus 12 $status"

function record() {
    # Create output directory
    now="$(date '+%a__%b%d__%H_%M_%S')"
    outputloc="$HOME/Videos/video_${now}"
    mkdir -p "$outputloc"/{vid,aud}

    # Detect primary monitor
    primary_info=$(xrandr | awk '/ primary / {print $4}')
    res=${primary_info%%+*}
    offset=${primary_info#*+}
    offset=${offset//+/,}

    # Screen capture only the primary monitor
    ffmpeg -video_size "$res" -f x11grab -r 30 -i "$DISPLAY+${offset}" -c:v h264 -qp 0 \
        "${outputloc}/vid/video_${now}.mkv" &
    echo $! > /tmp/recpid

    # Microphone (Default input monitor)
    ffmpeg -f pulse -i default \
        -af "afftdn=nf=-75" \
        "${outputloc}/aud/mic_${now}.wav" &
    echo $! > /tmp/audpid

    # Desktop audio (Default output monitor)
    ffmpeg -f pulse -i default.monitor \
        "${outputloc}/aud/desktop_${now}.wav" &
    echo $! > /tmp/deskaudpid

    # Metadata
    echo "$now" > /tmp/recording_timestamp
    echo "$outputloc" > /tmp/recording_outputdir
    echo "󰑊 Recording" > /tmp/recordingicon && $cmd

    notify-send "Recording started"
}

function end() {
    kill -15 "$(cat /tmp/recpid)" "$(cat /tmp/audpid)" "$(cat /tmp/deskaudpid)"
    wait

    now=$(cat /tmp/recording_timestamp)
    outputloc=$(cat /tmp/recording_outputdir)

    # Call merge script to merge recording files
    merge_rec "$outputloc" "$now"

    $cmd

    rm -fv /tmp/recordingicon /tmp/*pid /tmp/recording_timestamp /tmp/recording_outputdir

    notify-send "Recording ended and merged"
}

# If the recording pid exists, end recording. If not, start recording
([[ -f /tmp/recpid ]] && end && exit 0) || record
