#!/bin/env bash

# rofi prompt
options="Lock\nLogout\nReboot\nShutdown"
choice=$(echo -e "$options" | rofi -dmenu -p "Power Menu")

case "$choice" in
    Lock)
        slock
        ;;
    Logout)
        # Try graceful termination first
        loginctl terminate-user "$USER" || pkill -15 xinit
        ;;
    Reboot)
        systemctl reboot
        ;;
    Shutdown)
        systemctl poweroff
        ;;
    *)
        ;;
esac
