#!/bin/env bash

set -euo pipefail

# Source utils
[[ -f "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils" ]] && \
    source "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils"

status="${STATUSBAR:-dwmblocks}"

pkill "$status" && "$status" & disown
echo "Restarted: $status"
