#!/bin/env bash

# Ensure ffmpeg is installed
if ! command -v ffmpeg &> /dev/null; then
    echo "Error: ffmpeg not found. Please install it first."
    exit 1
fi

INRES="1280x720" # input resolution
OUTRES="1280" # output resolution horizontal. vertical is calculated.
FPS="30" # target FPS
GOP="60" # i-frame interval, should be double of FPS,
GOPMIN="30" # min i-frame interval, should be equal to fps,
THREADS="3" # max 6
CBR="1500k" # constant bitrate (should be between 1000k - 3000k)
QUALITY="ultrafast"  # one of the many FFMPEG preset
AUDIO_SRATE="44100"
AUDIO_CHANNELS="2" #1 for mono output, 2 for stereo
AUDIO_ERATE="96k" #audio encoding rate
STREAM_KEY="$TWITCH_TOKEN" #your twitch stream key goes here
SERVER="ingest.global-contribute" # http://bashtech.net/twitch/ingest.php for list

ffmpeg -f x11grab -s "$INRES" -r "$FPS" -i :0.0 \
    -f alsa -i pulse -f alsa -i pulse \
    -f flv -filter_complex amix=inputs=2 -ac $AUDIO_CHANNELS -b:a $AUDIO_ERATE -ar $AUDIO_SRATE \
    -vcodec libx264 -g $GOP -keyint_min $GOPMIN -b:v $CBR -minrate $CBR \
    -maxrate $CBR -vf "scale=$OUTRES:-1,format=yuv420p"\
    -preset $QUALITY -acodec libmp3lame -threads $THREADS -strict normal \
    -bufsize $CBR "rtmp://$SERVER.live-video.net/app/$STREAM_KEY"
