#!/bin/env bash

set -euo pipefail

# Source utils
[[ -f "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils" ]] && \
    source "${XDG_SCRIPTS_HOME:-$HOME/.local/scripts}/utils"

flatpak run io.github.dweymouth.supersonic & disown
