#!/bin/env bash

# Load theme
THEME=$(cat "${XDG_CACHE_HOME:-$HOME/.cache}/theme")

# Get connected monitors
MONITORS=()
while IFS= read -r monitor; do
    MONITORS+=("$monitor")
done < <(xrandr | grep " connected" | cut -d ' ' -f1)
NUM_MONITORS=${#MONITORS[@]}

# Select up to NUM_MONITORS wallpapers
WALLS=()
while IFS= read -r line; do
    WALLS+=("$line")
done < <(sxiv -r -q -o -t -n "$NUM_MONITORS" "${HOME}/Pictures/Wallpapers/${THEME:-other}/"*)

# Exit if not enough wallpapers selected
if [[ ${#WALLS[@]} -ne $NUM_MONITORS ]]; then
    echo "Please select exactly $NUM_MONITORS wallpapers"
    exit 1
fi

# Set wallpapers on monitors
for i in "${!MONITORS[@]}"; do
    xwallpaper --output "${MONITORS[i]}" --stretch "${WALLS[i]}"
    echo "Wallpaper set on ${MONITORS[i]} to ${WALLS[i]}"
done
