#!/bin/env bash

set -euo pipefail

# Ensure pamixer is installed
if ! command -v pamixer &> /dev/null; then
    echo "Error: pamixer is not installed."
    exit 1
fi

opt="${1:-}"
num="${2:-5}"

volume_inc() {
    pamixer -i "$num"
    pkill -RTMIN+16 slstatus
}

volume_dec() {
    pamixer -d "$num"
    pkill -RTMIN+16 slstatus
}

volume_togglemute() {
    pamixer --toggle-mute
    pkill -RTMIN+16 slstatus
}

volume_vol() {
    vol="$(pamixer --get-volume)"
    muted=$(pamixer --get-mute)
    if [[ "$vol" -eq 100 && "$muted" == "false" ]]; then
        echo " ${vol}%"  # Max volume
    elif [[ "$vol" -ge 50 && "$muted" == "false" ]]; then
        echo "󰕾 ${vol}%"  # High volume
    elif [[ "$vol" -ge 25 && "$muted" == "false" ]]; then
        echo "󰖀 ${vol}%"  # Medium volume
    elif [[ "$vol" -gt 0 && "$muted" == "false" ]]; then
        echo "󰕿 ${vol}%"  # Low volume
    else
        if [[ "$muted" == "true" ]]; then
            echo "󰝟  ${vol}%"  # Muted
        else
            echo "󰝟  Muted"  # 0
        fi
    fi
}

function help_menu() {
    cat <<EOF
Usage: $(basename "$0") [OPTION]

Options:
    --help, -h           Show this help menu
    --togglemute, -tm    Toggle mute
    --inc, -i            Increase volume by \${num}
    --dec, -d            Decrease volume by \${num}
    --printvol, -pv      Print current volume
EOF
}

case "$1" in
    --togglemute|-tm)
        volume_togglemute
        ;;
    --inc|-i)
        volume_inc
        ;;
    --dec|-d)
        volume_dec
        ;;
    --printvol|-pv) volume_vol ;;
    --help|-h) help_menu ;;
    *)
        echo "Error: '${opt:- }' Invalid option."
        help_menu
        exit 1
        ;;
esac
